name: upload assets

on: 
  push:
    tags:
      - "v*.*.*"
  
  # 允许您从“操作”选项卡手动运行此工作流程
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: 构建压缩包
        run: |
          bash ./scripts/build_ubuntu_focal.sh
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            vapor_app_ubuntu.tar.gz
# END